### ISSUE TITLE
install RAPIDS cuML automatically 

### ISSUE THREAD

**Issue by waynelapierre** [mlverse/cuda.ml#103]
Is it possible for this package to install RAPIDS cuML automatically when the package is installed? The torch R package automatically installs libtorch on my Linux OS.

**Comment by yitao-li** [comment]
@waynelapierre Thanks for the great suggestion! I think it's definitely something worth looking into.

There are at least 2 things to think about though:
- The only officially supported release channel of the cuML shared library is Conda at the moment. Is it appropriate to require users install Conda?
- Some alternative ways of installing the cuML shared library without having to install Conda are documented in https://github.com/yitao-li/cuml-installation-notes. I will need to think about whether any of those are reasonable to be run automatically.

**Comment by waynelapierre** [comment]
Installing Conda is definitely not a good idea.

**Comment by yitao-li** [comment]
@waynelapierre I agree that ideally there needs to be some way of facilitating the installation of the RAPIDS `cuML` shared lib, other than user manually going through the steps listed in  https://github.com/yitao-li/cuml-installation-notes or similar.

But I doubt there is any way to fully automate it. In particular, it would be a bad idea to attempt to automatically install non-trivial software components on a CRAN machine, and also it would not work there anyways if the CRAN machine does not have a CUDA-capable GPU (which is most likely the case).

Other R packages such as `sparklyr` or `arrow` which require non-trivial system dependencies are doing the same thing BTW, i.e., each provides some `install_<the dependency>()` function(s) that user can run to install some required system depedency, but such functions are never run automatically anywhere.

Let me know what you think.

**Comment by waynelapierre** [comment]
I totally agree with your point. Can you provide an install_<the dependency>() function for cuml4r?

**Comment by yitao-li** [comment]
@waynelapierre No it's not implemented yet. I was just saying that implementing `install_rapids_cuml_lib()` but users running it manually when necessary may be the plan, unless someone comes up with something better.

**Comment by waynelapierre** [comment]
great, that would be good way around
