### ISSUE TITLE
enable parallel builds by default

### ISSUE THREAD

**Issue by yitao-li** [mlverse/cuda.ml#185]

**Comment by dfalbel** [comment]
I'd check if CRAN allows parallel builds by default. AFAICT packages should be able to build with parallel make, but I am not sure you make that the default.

**Comment by yitao-li** [comment]
@dfalbel Good point 👍
I must admit I haven't even thought about CRAN 😅
Although the current plan is to only parallelize builds done by CMake, which (because of a happy conincidence) happens to have zero overlap with the CRAN, so I guess everything is still good.

**Comment by yitao-li** [comment]
Fun fact: I found out the only way to do it was to put 'MAKEFLAGS += -j<num>' in `Makevars`.
This was because the config phase and 'make all' phase are carried out by 2 processes from completely separate process trees, and there is no way for the former to modify the `MAKEFLAGS` env var of the latter.
Also, the `+=` operator is a bit hacky and may not even work in all cases (because of certain potential pecularities of Makefile rules) -- but it has worked reasonably well for the sort of Makefile rules {cuda.ml} has so far.
