### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by m-meli** [mlverse/cuda.ml#210]
Hi,

when i try to install cuda.ml from rstudio i get this error:
================================================================================
_* installing *source* package ‘cuda.ml’ ...
** package ‘cuda.ml’ successfully unpacked and MD5 sums checked
** using staged installation
** preparing to configure package 'cuda.ml' ...
*** configured file: 'src/CMakeLists.txt.in' => 'src/CMakeLists.txt'
Error in download.file(url, tmp) : 
  'url' must be a length-one character vector
Calls: source_file ... eval -> run_cmake -> download_libcuml -> download.file
In addition: Warning message:
In normalizePath(file.path(pkg_root(), "libcuml")) :
  path[1]="/tmp/Rtmprte04p/R.INSTALL15e1266387e65/cuda.ml/libcuml": No such file or directory
Execution halted
ERROR: configuration failed for package ‘cuda.ml’
`*` removing ‘/home/pino/R/x86_64-pc-linux-gnu-library/4.4/cuda.ml’
Warning in install.packages :
  installation of package ‘cuda.ml’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpOeaXnA/downloaded_packages’_
================================================================================

i think that something is change with cmake when FetchContent_Declare is used in cmake.

**Comment by m-meli** [comment]
> Hi,
> 
> # when i try to install cuda.ml from rstudio i get this error:
> _* installing _source_ package ‘cuda.ml’ ... ** package ‘cuda.ml’ successfully unpacked and MD5 sums checked ** using staged installation ** preparing to configure package 'cuda.ml' ... *** configured file: 'src/CMakeLists.txt.in' => 'src/CMakeLists.txt' Error in download.file(url, tmp) : 'url' must be a length-one character vector Calls: source_file ... eval -> run_cmake -> download_libcuml -> download.file In addition: Warning message: In normalizePath(file.path(pkg_root(), "libcuml")) : path[1]="/tmp/Rtmprte04p/R.INSTALL15e1266387e65/cuda.ml/libcuml": No such file or directory Execution halted ERROR: configuration failed for package ‘cuda.ml’ `*` removing ‘/home/pino/R/x86_64-pc-linux-gnu-library/4.4/cuda.ml’ Warning in install.packages : installation of package ‘cuda.ml’ had non-zero exit status
> 
> # The downloaded source packages are in
> ‘/tmp/RtmpOeaXnA/downloaded_packages’_
> i think that something is change with cmake when FetchContent_Declare is used in cmake.

The problem is the cuda version that must be 11.

**Comment by t-kalinowski** [comment]
Thank you for reporting back the solution!
